export const FETCH_CATEGORYPAGE_REQUEST = 'FETCH_CATEGORYPAGE_REQUEST'
export const FETCH_CATEGORYPAGE_SUCCESS = 'FETCH_CATEGORYPAGE_SUCCESS'
export const FETCH_CATEGORYPAGE_FAILURE = 'FETCH_CATEGORYPAGE_FAILURE'